# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Comment

on:
  push:
    branches: [ angular-v9-final ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Спасибо огромное :) на днях выложу сборку с переводом
